[package]
name = "hcaptcha-mmvm"
version = "0.1.0"
edition = "2024"

[dependencies]
oxc_allocator = "0.66.0"
oxc_ast = "0.66.0"
oxc_ast_visit = "0.66.0"
oxc_codegen = "0.66.0"
oxc_parser = "0.66.0"
oxc_semantic = "0.66.0"
oxc_span = "0.66.0"
oxc_syntax = "0.66.0"

anyhow = "1.0.98"
md5 = "0.7.0"